apiVersion: v1
kind: ResourceQuota
metadata:
  name: qa-resource-quota
  namespace: qa
spec:
  hard:
    pods: "10"
    requests.cpu: "1200m"
    limits.cpu: "1800m"
    requests.memory: "1229Mi" 
    limits.memory: "2Gi"
    persistentvolumeclaims: "5"
    requests.storage: "30Gi"