apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-resource-quota
  namespace: prod
spec:
  hard:
    pods: "15"
    requests.cpu: "1500m"
    limits.cpu: "2000m"
    requests.memory: "1536Mi"  
    limits.memory: "2560Mi"    
    persistentvolumeclaims: "10"
    requests.storage: "50Gi"