apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prod-binding
  namespace: prod
subjects:
  - kind: ServiceAccount
    name: prod
    namespace: prod
roleRef:
  kind: Role
  name: prod-role
  apiGroup: rbac.authorization.k8s.io