# This YAML file tests that  a Kubernetes Pod can access to AWS Secrets Manager from within an EKS cluster.
#kubectl apply -f test-secrets-access.yaml
#kubectl exec -it test-secrets-access -- bash
#aws secretsmanager get-secret-value --secret-id BookAdvisor_db_credentials --region eu-west-3 --query SecretString --output text
apiVersion: v1 
kind: Pod
metadata:
  name: test-secrets-access
  namespace: default
spec:
  containers:
  - name: aws-cli
    image: amazon/aws-cli
    command: ["sleep", "3600"]  # Keep running
  # If using IAM roles for service accounts, add:
  serviceAccountName: default  # Use your app's service account if you have one
  restartPolicy: Never